site_name: Incan Documentation
theme:
  name: material
  palette:
        - scheme: slate
  features:
        - navigation.tabs
        - navigation.sections
        - navigation.expand

extra_css:
    - stylesheets/extra.css
