site_name: Incan
docs_dir: docs

theme:
  name: material
  palette:
        - scheme: slate
  features:
        - navigation.tabs
        - toc.integrate

extra_css:
    - stylesheets/incan.css

extra:
  generator: false

nav:
    - Home: index.md

static_templates:
    - 404.html
