site_name: Incan
docs_dir: docs

theme:
  name: material
  palette:
        - scheme: slate
  features:
        - navigation.tabs
        - toc.integrate

extra:
  generator: false
  css:
        - stylesheets/incan.css

nav:
    - Home: index.md

static_templates:
    - 404.html